---
title: "Readings"
---

Bollen, K.A. and Pearl, J. (2012) Eight myths about causality and Structural Equation Models. In Handbook of Structural Equation Modeling.  R. Hoyle, ed. [<a href="http://byrneslab.net/classes/sem_pdfs/General/bollen%20and%20pearl%208%20myths%20about%20sem.pdf">pdf</a>]<br /><br />

Byrnes, J.E., Reed, D.C., Cardinale, B.J., Cavanaugh, K.C., Holbrook, S.J. & Schmitt, R.J. (2011). Climate driven increases in storm frequency simplify kelp forest food webs. Global Change Biology, 17: 2513-2524.[<a href="http://byrneslab.net/classes/sem_pdfs/examples/Byrnes%20et%20al%202011%20GCB.pdf">pdf</a>]
<br /><br />

Grace, J.B.  (2010) Structural Equation Modeling for Observational Studies.  Journal of Wildlife Management, 72:14-22 [<a href="http://byrneslab.net/classes/sem_pdfs/intro_texts/Grace%202010%20Journal%20of%20Wildlife%20Research.pdf">pdf</a>]
<br /><br />

Grace J.B., Anderson TM, Olff H, Scheiner SM (2010) On the specification of structural equation models for ecological systems. Ecological Monographs, 80, 67-87. [<a href="http://byrneslab.net/classes/sem_pdfs/General/Grace%20et%20al%202010%20Ecological%20Monographs.pdf">pdf</a>]
<br /><br />

Grace J.B., Bollen KA (2005) Interpreting the Results from Multiple Regression and Structural Equation Models. Bulletin of the Ecological Society of America, 86, 283-295.[<a href="http://byrneslab.net/classes/sem_pdfs/General/Grace%20and%20Bollen%202005%20Bull%20Ecol%20Soc%20Amer.pdf">pdf</a>]
<br /><br />

Grace, J.B. & Jutila, H. (1999). The relationship between species density and community biomass in grazed and ungrazed coastal meadows. Oikos, 398-408. [<a href="http://byrneslab.net/classes/sem_pdfs/examples/Grace%20and%20Jutila%201999.pdf">pdf</a>]<br /><br />

Mancera, J.E., Meche, G.C., Cardona-Olarte, P.P., Castañeda-Moya, E., Chiasson, R.L., Geddes, N.A., et al. (2005). Fine-scale spatial variation in plant species richness and its relationship to environmental conditions in coastal marshlands. Plant Ecol., 178, 39-50. [<a href="http://byrneslab.net/classes/sem_pdfs/spatial%20autocorrelation/Mancera&&2005.pdf">pdf</a>]<br /><br />

Matsueda, R.L.  (2012)  Key advances in the history of structural equation modeling.  In Handbook of Structural Equation Modeling.  R. Hoyle, ed. [<a href="http://byrneslab.net/classes/sem_pdfs/General/Matsueda%202012%20history.pdf">pdf</a>]
<br /><br />

Pearl, J. (2009) Defending the causal interpretation of SEM. In Causality, 2nd Ed. [<a href="http://byrneslab.net/classes/sem_pdfs/causality/pearl%20defending%20sem.pdf">pdf</a>]
<br /><br />

Pearl, J. (2012) The causal foundations of Structural Equation Modeling. In Handbook of Structural Equation Modeling.  R. Hoyle, ed. [<a href="../http://jarrettbyrnes.info/sem_pdfs/causality/pearl%20causal%20foundations%20of%20SEM.pdf">pdf</a>]
<br /><br />

Shipley, B. (2004) Analysing the allometry of multiple interacting traits. Perspect Plant Ecol, 6, 235-241. [<a href="sem_pdfs/d-sep/shipley%202004%20dsep%20allometry.pdf">pdf</a>]
<br /><br />

Shipley, B. (2009) Confirmatory path analysis in a generalized multilevel context. Ecology, 90: 363-368.[<a href="http://byrneslab.net/classes/sem_pdfs/d-sep/Shipley%202009%20dsep%20with%20multilevel%20models.pdf">pdf</a>] [<a href="http://byrneslab.net/classes/sem_pdfs/d-sep/Shipley%202009%20R%20example.pdf">R appendix</a>]
<br /><br />

See also the pdfs in <a href="http://byrneslab.net/classes/sem_pdfs">this folder</a> for more topic-specific readings.

u/p: semclass for all