---
title: "Course Schedule"
---
The general schedule for the course is below. Please note, for readings the u/p is semclass for both. For code, please see [this dropbox](https://www.dropbox.com/sh/objbunt4wxdlnxb/AAB38yRdxi62BlMC1ca_SYPJa?dl=0) for a static view. During the course itself, I'll give you share access so that you can update files as things change. Please [run this script](./files/scripts/Install_Required_Packages.R) in R to install the packages you will need for the course before day 1.

## Day 1. Introduction to SEM
__Overview:__  We discuss just what is SEM. Along the way we'll discuss it's origins, give a general example of moving from a traditional ANOVA-esque framework, and finally discuss how to build a well-justified causal model. Causality will be central, and we won't pull any punches! We'll end the day by starting to talk about how to fit SEMs using likelihood using covariance-based estimation with likelihood.  
__Lectures:__  [What is SEM? A Practical and Historical Overview](lecture_pdfs/SEM_Intro_And_History.pdf)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	[Anatomy of SEM](lecture_pdfs/Anatomy_of_SEM.pdf)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	[Building Multivariate Causal Models](lecture_pdfs/Multivariate_Causal_Models.pdf), [code](files/scripts/multivariate_causal_models.R)  
__Readings:__  [Grace 2010](http://byrneslab.net/classes/sem_pdfs/General/Grace%20et%20al%202010%20Ecological%20Monographs.pdf) (overview), [Whalen et al. 2013](http://byrneslab.net/classes/sem_pdfs/examples/Whalen_et_al_2013_Ecology.pdf) (example) (note: semclass/semclass for pdfs)  
__Optional Reading:__ [Matsueda 2012](http://byrneslab.net/classes/sem_pdfs/General/Matsueda%202012%20history.pdf) (history), [Pearl 2012a](http://byrneslab.net/classes/sem_pdfs/causality/pearl-causality-review.pdf) (history of causality)
\
\

## Day 2. Covariance Based SEM  
__Overview:__  We'll pick up where we left off discussing covariance-based estimation. We'll spend time discussing how we evaluate an SEM and what we report. We'll end the day exploring the concept of latent variables - variables for which we do not actually have a measured variable, but for which we have one or more indicators.  
__Lectures:__  	[Engines of SEM: Covariance-Based Estimation](lecture_pdfs/Intro_to_Likelihood_Fitting.pdf), [code](files/scripts/Likelihood_Fitting.R)    
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [What does it mean to evaluate a multivariate hypothesis?](lecture_pdfs/Assesing_Likelihood_Fits.pdf), [code](files/scripts/Assessing_Likelihood.R), [fitted_lavaan.R](files/scripts/fitted_lavaan.R)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Latent Variable models](lecture_pdfs/Latent_Variables.pdf), [code](files/scripts/Latent_variables.R)  
__Readings:__  [Grace and Bollen 2005](http://byrneslab.net/classes/sem_pdfs/General/Grace & Bollen 2005 Bull Ecol Soc Amer.pdf)
\
\

## Day 3. Piecewise SEM  
__Overview:__  We move beyond covariance based techniques into local estimation techniques that embrace the graph theoretic approach to SEM via the `piecewiseSEM` package by Jon Lefcheck.  
__Lectures:__  	Engines of SEM: Local Estimation with piecewiseSEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A Nonlinear, Non-normal world  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Mixed Models in SEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Categorical Variables and Multigroup Analysis  
__Readings:__  [piecewiseSEM vignette](http://jslefche.github.io/piecewiseSEM/articles/piecewiseSEM.html), [Shipley 2009](http://byrneslab.net//classes/sem_pdfs/d-sep/Shipley%202009%20dsep%20with%20multilevel%20models.pdf), [Lefcheck 2016](http://byrneslab.net//classes/sem_pdfs/d-sep/Lefcheck_2016_piecewiseSEM.pdf)
\
\

## Day 4. Special Topics in SEM  
__Overview:__  This day varies quite a bit, depending on the current class. It's a potpurri of more advances topics, not all of which will be covered.  
__Lectures:__  Engines of SEM: Bayesian SEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Spatial Data in SEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Timseries and Temporal Autocorrelation in SEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Whole-System Prediction with SEM  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Composite Variables   
__Readings:__   [brms and SEM](https://rpubs.com/jebyrnes/brms_bayes_sem). [causal model structure and random effects](https://rpubs.com/jebyrnes/causal_mods)
\
\

## Day 5. Open Lab and Presentations  
__Overview:__  In the morning, we'll have an open lab. Students will work on their own data and projects with an aim to building a 2-3 slide powerpoint presentation detailing 1. The problem/system, 2. The model they built, and 3. The Final result and any challenges. We'll present these in the afternoon, hopefully in a convivial atmosphere, after a brief primer on warming up for a talk you are nervous about!  
__Lectures:__  How to fool yourself with SEM!
\
\

